apiVersion: v1
kind: Service
metadata:
  name: laravel-service
spec:
  type: LoadBalancer  
  selector:
    app: laravel-app
  ports:
    - protocol: TCP
      port: 80          # External port
      targetPort: 9000  # Laravel app port inside the container

